# config/services.yaml
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\State\AvatarSetOwnerProcessor:
        arguments:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'

    App\State\AvatarDeleteProcessor:
        arguments:
            $removeProcessor: '@api_platform.doctrine.orm.state.remove_processor'

    App\State\AnimationDeleteProcessor:
        arguments:
            $removeProcessor: '@api_platform.doctrine.orm.state.remove_processor'

