<?php

return [
    [
        'id' => 'glm-5.1',
        'name' => 'GLM-5.1',
        'description' => 'Latest flagship GLM model with stronger coding and long-horizon agent work, available on both the standard API and the GLM Coding Plan endpoint.',
        'group' => 'flagship',
        'releasedAt' => '2026-04-07',
        'contextLength' => 200000,
        'isRecommended' => true,
    ],
    [
        'id' => 'glm-5',
        'name' => 'GLM-5',
        'description' => 'Latest flagship general-purpose GLM model for agent-style tasks.',
        'group' => 'flagship',
        'releasedAt' => '2025-12-22',
        'contextLength' => 200000,
        'isRecommended' => true,
    ],
    [
        'id' => 'glm-4.7',
        'name' => 'GLM-4.7',
        'description' => 'Strong general-purpose model for complex tasks and coding.',
        'group' => 'general',
        'releasedAt' => '2025-12-22',
        'contextLength' => 200000,
        'isRecommended' => true,
    ],
    [
        'id' => 'glm-4.7-flash',
        'name' => 'GLM-4.7-Flash',
        'description' => 'Fast GLM-4.7 variant for lightweight chat when enabled by your account billing or plan.',
        'group' => 'fast',
        'releasedAt' => '2025-12-22',
        'contextLength' => 200000,
        'isRecommended' => false,
    ],
    [
        'id' => 'glm-4.7-flashx',
        'name' => 'GLM-4.7-FlashX',
        'description' => 'Speed-focused GLM-4.7 variant whose availability depends on your account billing setup.',
        'group' => 'fast',
        'releasedAt' => '2025-12-22',
        'contextLength' => 200000,
        'isRecommended' => false,
    ],
    [
        'id' => 'glm-4.6',
        'name' => 'GLM-4.6',
        'description' => 'Earlier strong GLM generation for stable general chat and coding.',
        'group' => 'general',
        'releasedAt' => '2025-10-01',
        'contextLength' => 200000,
        'isRecommended' => false,
    ],
    [
        'id' => 'glm-4.5',
        'name' => 'GLM-4.5',
        'description' => 'Powerful reasoning-focused GLM-4.5 base model.',
        'group' => 'reasoning',
        'releasedAt' => '2025-07-28',
        'contextLength' => 128000,
        'isRecommended' => false,
    ],
    [
        'id' => 'glm-4.5-air',
        'name' => 'GLM-4.5-Air',
        'description' => 'Cost-effective GLM 4.5 variant for strong general chat and coding.',
        'group' => 'fast',
        'releasedAt' => '2025-07-28',
        'contextLength' => 128000,
        'isRecommended' => true,
    ],
    [
        'id' => 'glm-4.5-airx',
        'name' => 'GLM-4.5-AirX',
        'description' => 'Faster premium lightweight GLM-4.5 family variant.',
        'group' => 'fast',
        'releasedAt' => '2025-07-28',
        'contextLength' => 128000,
        'isRecommended' => false,
    ],
    [
        'id' => 'glm-4.5-flash',
        'name' => 'GLM-4.5-Flash',
        'description' => 'Fast GLM-4.5 variant useful for lightweight chat when enabled by your account billing or plan.',
        'group' => 'fast',
        'releasedAt' => '2025-07-28',
        'contextLength' => 128000,
        'isRecommended' => false,
    ],
    [
        'id' => 'glm-4-flash-250414',
        'name' => 'GLM-4-Flash-250414',
        'description' => 'Legacy GLM 4 flash model still listed in the current BigModel API options.',
        'group' => 'legacy',
        'releasedAt' => '2025-04-14',
        'contextLength' => 128000,
        'isRecommended' => false,
    ],
    [
        'id' => 'glm-4-flashx-250414',
        'name' => 'GLM-4-FlashX-250414',
        'description' => 'Legacy faster GLM 4 flash variant still listed in the current BigModel API options.',
        'group' => 'legacy',
        'releasedAt' => '2025-04-14',
        'contextLength' => 128000,
        'isRecommended' => false,
    ],
];
