<?php

return [
    [
        'id' => 'MiniMax-M2.7',
        'name' => 'MiniMax-M2.7',
        'description' => 'Latest top-tier MiniMax text model focused on real-world engineering, office work, and richer character interaction.',
        'group' => 'flagship',
        'releasedAt' => '2026-03-18',
        'contextLength' => 204800,
        'isRecommended' => true,
    ],
    [
        'id' => 'MiniMax-M2.7-highspeed',
        'name' => 'MiniMax-M2.7 Highspeed',
        'description' => 'Faster M2.7 variant for lower-latency interactions with the same core capabilities.',
        'group' => 'fast',
        'releasedAt' => '2026-03-18',
        'contextLength' => 204800,
        'isRecommended' => true,
    ],
    [
        'id' => 'MiniMax-M2.5',
        'name' => 'MiniMax-M2.5',
        'description' => 'Previous flagship MiniMax text model for coding, tools, and complex tasks.',
        'group' => 'flagship',
        'releasedAt' => '2026-02-01',
        'contextLength' => 204800,
        'isRecommended' => false,
    ],
    [
        'id' => 'MiniMax-M2.5-highspeed',
        'name' => 'MiniMax-M2.5 Highspeed',
        'description' => 'Faster M2.5 variant for lower-latency interactions.',
        'group' => 'fast',
        'releasedAt' => '2026-02-01',
        'contextLength' => 204800,
        'isRecommended' => false,
    ],
    [
        'id' => 'MiniMax-M2.1',
        'name' => 'MiniMax-M2.1',
        'description' => 'Strong multilingual programming and reasoning model.',
        'group' => 'general',
        'releasedAt' => '2025-12-22',
        'contextLength' => 204800,
        'isRecommended' => false,
    ],
    [
        'id' => 'MiniMax-M2.1-highspeed',
        'name' => 'MiniMax-M2.1 Highspeed',
        'description' => 'Faster M2.1 variant for responsive chat and agent loops.',
        'group' => 'fast',
        'releasedAt' => '2025-12-22',
        'contextLength' => 204800,
        'isRecommended' => false,
    ],
    [
        'id' => 'MiniMax-M2',
        'name' => 'MiniMax-M2',
        'description' => 'Earlier agentic reasoning model still supported in current docs.',
        'group' => 'general',
        'releasedAt' => '2025-12-22',
        'contextLength' => 204800,
        'isRecommended' => false,
    ],
];
